Adding information to the README.md file
redhat-beyond/Xpense pull request #3
Opened 2022-03-05 11:29 UTC by ShellyGolden

Adding information about Xpense project

2022-03-05 12:43 UTC, LiorKGOW requested changes
nicely written @ShellyGolden  
maybe you should add the names of the participants in our group :)

2022-03-05 13:21 UTC, ShellyGolden commented
Thanks @LiorKGOW 

I added the list

2022-03-05 13:21 UTC, LiorKGOW approved these changes

2022-03-05 18:53 UTC, bregman-arie commented on README.md
> +It’s main objective is to monitor housekeeping related income and expenses.
Its

2022-03-07 07:57 UTC, yuvalk commented
please squash commits

2022-03-07 08:00 UTC, yuvalk commented
commit msg subject (first line) should be phrased as "if applied this commit will ..." (add README.md)
then subject can say something about the WHY 
you dont usually need to describe the content, as that is visible from the commit diff.
in special cases, you can add a second paragraph with such explanations (when you think it's appropriate)
and in complicated cases, I sometimes add a 3rd paragraph with even more technical explanations and references.

remember, you should think of the git history as of a novel, you should be telling the story of the code

2022-03-07 09:48 UTC, ronyyosef approved these changes

2022-03-07 13:26 UTC, ShellyGolden commented
I squashed the commits, and changed the commit msg
@yuvalk

2022-03-07 16:06 UTC, LiorKGOW approved these changes
looks better as one commit :)
GJ Shelly

2022-03-07 19:06 UTC, shlior7 commented
#6 issue to resolve

2022-03-07 20:02 UTC, merged