Add Global page charts
redhat-beyond/Xpense pull request #76
Opened 2022-04-18 13:51 UTC by ronyyosef

Add the two charts in the global page
Filter options will be add in diffrent PR

2022-04-18 14:13 UTC, ShellyGolden reviewed
looks good
I left comments
please change the title of the PR

2022-04-18 14:13 UTC, ShellyGolden commented on scripts/create_mock_data.py
> +        print(i)
this line is necessary?

2022-04-18 14:13 UTC, ShellyGolden commented on static/css/global.css
> +}
you need to add new line at the end of the file

2022-04-18 14:28 UTC, ronyyosef commented on scripts/create_mock_data.py
> +        print(i)
Nope, my bad

2022-04-18 14:30 UTC, ronyyosef commented
I will add tests for the query soon

2022-04-18 15:04 UTC, LiorKGOW requested changes

2022-04-18 15:04 UTC, LiorKGOW commented on templates/global/chart.html
> +                            backgroundColor: randomColors,
Every expense gets a different random color,
Very nice

2022-04-18 19:48 UTC, shlior7 reviewed
I think we can also add the tests from the draft 
Or at least some of them

https://github.com/redhat-beyond/Xpense/blob/fd9f97d03e20e57581f4d8272a0805f9506c0e7f/tests/global_tests.py

2022-04-18 20:25 UTC, ronyyosef commented
I added the tests

2022-04-19 06:42 UTC, orIsrael approved these changes

2022-04-19 14:05 UTC, ShellyGolden approved these changes

2022-04-19 19:00 UTC, svatares approved these changes

2022-04-19 19:00 UTC, merged